set(JAVA_HOME D:/Tools/labsjdk-ce-17.0.6-jvmci-22.3-b13)
set(JNI_COMMON_INCLUDE ${JAVA_HOME}/include)

message("PROJECT_NAME = " ${PROJECT_NAME})
set(OUTPUT_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../build)
message("CMAKE_BUILD_RPATH = " ${OUTPUT_PATH})

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${OUTPUT_PATH})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${OUTPUT_PATH})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${OUTPUT_PATH})