message("--- Platform info ---")
message("  Platform = ${CMAKE_SYSTEM_NAME} v${CMAKE_SYSTEM_VERSION}")
message("  Compiler = ${CMAKE_CXX_COMPILER}")
message("    ${CMAKE_CXX_COMPILER_ID} v.${CMAKE_CXX_COMPILER_VERSION}")
message("  BUILD_TYPE = ${CMAKE_BUILD_TYPE}")

if(${CMAKE_SIZEOF_VOID_P} EQUAL 8)
    message("    target arch = x86-64, CPU = ${CMAKE_SYSTEM_PROCESSOR}")
    set(TARGET_ARCH x64)
elseif(${CMAKE_SIZEOF_VOID_P} EQUAL 4)
    set(TARGET_ARCH x86-64)
    if (NOT "${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
        message(FATAL_ERROR MSVC compiler is expected for ${TARGET_ARCH})
    endif()
    message("    target arch = x86, CPU = ${CMAKE_SYSTEM_PROCESSOR}")
endif()