/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dxfeed_api_JNIDXFeedEventListener */

#ifndef _Included_com_dxfeed_api_JNIDXFeedEventListener
#define _Included_com_dxfeed_api_JNIDXFeedEventListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dxfeed_api_JNIDXFeedEventListener
 * Method:    nOnEventListener
 * Signature: (I[B[D[BJ)V
 */
JNIEXPORT void JNICALL Java_com_dxfeed_api_JNIDXFeedEventListener_nOnEventListener
  (JNIEnv *, jclass, jint, jbyteArray, jdoubleArray, jbyteArray, jlong);

/*
 * Class:     com_dxfeed_api_JNIDXFeedEventListener
 * Method:    nClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_dxfeed_api_JNIDXFeedEventListener_nClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
