/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dxfeed_api_DxSubscriptionJni */

#ifndef _Included_com_dxfeed_api_DxSubscriptionJni
#define _Included_com_dxfeed_api_DxSubscriptionJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dxfeed_api_DxSubscriptionJni
 * Method:    nOnEventListener
 * Signature: (I[B[D[BJJ)V
 */
JNIEXPORT void JNICALL Java_com_dxfeed_api_DxSubscriptionJni_nOnEventListener
  (JNIEnv *, jclass, jint, jbyteArray, jdoubleArray, jbyteArray, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
