/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dxfeed_api_DxFeedJni */

#ifndef _Included_com_dxfeed_api_DxFeedJni
#define _Included_com_dxfeed_api_DxFeedJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dxfeed_api_DxFeedJni
 * Method:    nOnStateChangeListener
 * Signature: (IIJJ)V
 */
JNIEXPORT void JNICALL Java_com_dxfeed_api_DxFeedJni_nOnStateChangeListener
  (JNIEnv *, jclass, jint, jint, jlong, jlong);

/*
 * Class:     com_dxfeed_api_DxFeedJni
 * Method:    nOnEventListener
 * Signature: (I[B[D[BJJ)V
 */
JNIEXPORT void JNICALL Java_com_dxfeed_api_DxFeedJni_nOnEventListener
  (JNIEnv *, jclass, jint, jbyteArray, jdoubleArray, jbyteArray, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
