/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dxfeed_api_JniTest */

#ifndef _Included_com_dxfeed_api_JniTest
#define _Included_com_dxfeed_api_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dxfeed_api_JniTest
 * Method:    nOnQuoteEventListener
 * Signature: (I[B[D[BJ)V
 */
JNIEXPORT void JNICALL Java_com_dxfeed_api_JniTest_nOnQuoteEventListener
  (JNIEnv *, jclass, jint, jbyteArray, jdoubleArray, jbyteArray, jlong);

/*
 * Class:     com_dxfeed_api_JniTest
 * Method:    nOnStateChangeListener
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_dxfeed_api_JniTest_nOnStateChangeListener
  (JNIEnv *, jclass, jint, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
