/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dxfeed_api_JNIPropertyChangeListener */

#ifndef _Included_com_dxfeed_api_JNIPropertyChangeListener
#define _Included_com_dxfeed_api_JNIPropertyChangeListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dxfeed_api_JNIPropertyChangeListener
 * Method:    nOnStateChangeListener
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_com_dxfeed_api_JNIPropertyChangeListener_nOnStateChangeListener
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     com_dxfeed_api_JNIPropertyChangeListener
 * Method:    nClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_dxfeed_api_JNIPropertyChangeListener_nClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
