/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dxfeed_api_DxEndpointJni */

#ifndef _Included_com_dxfeed_api_DxEndpointJni
#define _Included_com_dxfeed_api_DxEndpointJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dxfeed_api_DxEndpointJni
 * Method:    nOnStateChangeListener
 * Signature: (IIJJ)V
 */
JNIEXPORT void JNICALL Java_com_dxfeed_api_DxEndpointJni_nOnStateChangeListener
  (JNIEnv *, jclass, jint, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
